version: '3.3'
services:

  redis:
    image: redis:6.2.6
    restart: always
    expose:
      - '6379'
    command: redis-server # --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - $HOME/data/db/redis:/data

  exam:
    build:
      context: .
      dockerfile: Dockerfile
    image: mnist-gnn:v0.1.0
    container_name: mnist-gnn
    network_mode: host
    shm_size: '32gb'
    stdin_open: true
    tty: true
    user: mtx
#   restart: always
#   ports:
#     - "28888:8888"

    volumes:
      - "$HOME/data/mnist_gnn:/home/mtx/data"
      - ".:/home/mtx/code"
#   command: ["bash"]
