version: '3.3'
services:
  exam:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        http_proxy: socks5://127.0.0.1:10800
        https_proxy: socks5://127.0.0.1:10800
    image: mnist-gnn
    container_name: mnist-gnn
    stdin_open: true
    tty: true
    user: mtx
#   restart: always
#   ports:
#     - "28888:8888"

    volumes:
      - "$HOME/data/mnist_gnn:/home/mtx/data"
#   command: ["bash"]
