FROM python:3.8-slim
MAINTAINER TX Mao <mtianxiang@gmail.com>

RUN pip install \
    --trusted-host nexus.storage.datalab -i http://nexus.storage.datalab/repository/pypi/simple\
    flask-sock redis Flask

WORKDIR /code
